## Project requirements (PEP 518, https://python-poetry.org/).


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.black]
line-length = 79
target-version = ["py36"]


[tool.isort]
line_length = 79
profile = "black"


[tool.mypy]
incremental = true
cache_dir = ".mypy"
pretty = true
show_error_codes = true
show_error_context = true

check_untyped_defs = true
strict_optional = true
no_implicit_optional = true

warn_no_return = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_ignores = true


[tool.poetry]
name = "soteria_webapp"
version = "0.1.0"
description = "SOTERIA web application"
license = "Apache-2.0"
authors = ["Brian Aydemir <baydemir@morgridge.org>"]
packages = [{ include = "registry" }]


[tool.poetry.dependencies]
python = ">=3.6.8,<3.7"
dataclasses = "^0.8"
Flask = "^2.0.1"
Flask-Assets = "^2.0"
ldap3 = "^2.9.1"
libsass = "^0.21.0"
requests = "^2.26.0"
typing-extensions = "^3.10.0.2"


[tool.poetry.dev-dependencies]
bandit = "^1.7.0"
black = "^21.9b0"
docutils = "^0.17.1"
isort = "^5.9.3"
mypy = "^0.910"
pre-commit = "^2.15.0"
pylint = "^2.11.1"
pytype = "^2021.9.27"
"ruamel.yaml.cmd" = "^0.5.7"
safety = "^1.10.3"
types-dataclasses = "^0.1.7"
types-requests = "^2.25.9"


[tool.pylint.messages-control]
max-line-length = 79
disable = "invalid-name,missing-class-docstring,missing-function-docstring"
