# This project uses Poetry <https://python-poetry.org/>.

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ["py36"]

[tool.isort]
line_length = 88
profile = "black"

[tool.poetry]
name = "harbor_user_registry"
version = "0.1.0"
description = "Web application for managing the users of a Harbor instance"
authors = ["Brian Aydemir <baydemir@morgridge.org>"]
maintainers = ["OSG Software <support@opensciencegrid.org>"]
license = "Apache-2.0"
packages = [{ include = "registry" }]

[tool.poetry.dependencies]
python = ">=3.6.8,<3.7"
Flask = "^2.0.1"
requests = "^2.25.1"
Flask-Assets = "^2.0"

[tool.poetry.dev-dependencies]
bandit = "^1.7.0"
black = "^21.5b2"
docutils = "^0.17.1"
isort = "^5.8.0"
mypy = "^0.812"
pre-commit = "^2.13.0"
pylint = "^2.8.3"
pytype = "^2021.5.25"
safety = "^1.10.3"

[tool.pylint.messages-control]
max-line-length = 88
disable = "invalid-name,missing-class-docstring,missing-function-docstring"
