# This project uses Poetry for packaging and dependency management.
# See https://python-poetry.org/ for more information.


[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]


[tool.black]
line-length = 88
target-version = ["py36"]


[tool.isort]
line_length = 88
profile = "black"


[tool.mypy]
incremental = true
cache_dir = "~/.cache/mypy"
show_error_codes = true
show_error_context = true

check_untyped_defs = true
strict_optional = true
no_implicit_optional = false

warn_no_return = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_ignores = true


[tool.poetry]
name = "soteria_registry"
version = "0.1.0"
description = "SOTERIA registry web application"
license = "Apache-2.0"
authors = ["Brian Aydemir <baydemir@morgridge.org>"]
maintainers = ["OSG Software <support@opensciencegrid.org>"]
packages = [{ include = "registry" }]


[tool.poetry.dependencies]
python = ">=3.6.8,<3.7"
Flask = "^2.0.1"
Flask-Assets = "^2.0"
requests = "^2.25.1"


[tool.poetry.dev-dependencies]
bandit = "^1.7.0"
black = "^21.6b0"
docutils = "^0.17.1"
isort = "^5.9.1"
mypy = "^0.910"
pre-commit = "^2.13.0"
pylint = "^2.8.3"
pytype = "^2021.6.17"
safety = "^1.10.3"
types-requests = "^2.25.0"


[tool.pylint.messages-control]
max-line-length = 88
disable = "invalid-name,missing-class-docstring,missing-function-docstring"
