# This project is managed by Poetry.
#
# References:
# - https://www.python.org/dev/peps/pep-0518/
# - https://python-poetry.org

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ["py36"]

[tool.isort]
line_length = 88
profile = "black"

[tool.poetry]
name = "harbor_user_registry"
version = "0.1.0"
description = "Registry for users of a Harbor instance"
authors = ["Brian Aydemir <baydemir@morgridge.org>"]
maintainers = ["OSG Software <support@opensciencegrid.org>"]
license = "Apache-2.0"
packages = [{ include = "registry" }]

[tool.poetry.dependencies]
python = ">=3.6.8,<3.7"
Flask = "^2.0.1"

[tool.poetry.dev-dependencies]
bandit = "^1.7.0"
black = "^21.5b1"
isort = "^5.8.0"
mypy = "^0.812"
pre-commit = "^2.13.0"
pylint = "^2.8.2"
pytype = "^2021.5.19"
safety = "^1.10.3"

[tool.pylint.messages-control]
max-line-length = 88
disable = "C0103,C0115,C0116"  # invalid names and missing docstrings
